url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "JoshuaDaigleCV" # the subpath of your site, e.g. /blog
title: "Joshua Daigle CV" # the name of your site, e.g. ACME Corp.
